### ISSUE TITLE
翻译插件不好用了 大佬看看

### ISSUE THREAD

**Issue by masterhan1991** [getActivity/StudioPlugins#2]
翻译失败: 未知错误

>Plugin v3.1-201  
>Android Studio 4.1  
>Build #AI-201.8743.12.41.6858069, built on September 23, 2020  
>Runtime version: 1.8.0_242-release-1644-b01 amd64  
>VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o  
>OS: Windows 10 10.0

```
cn.yiiguxing.plugin.translate.trans.TranslateException: Google 翻译 :: 翻译失败: 未知错误
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:129)
	at cn.yiiguxing.plugin.translate.trans.TranslateService$translate$$inlined$executeOnPooledThread$1.run(Applications.kt:184)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:255)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.HttpRetryException: cannot retry due to redirection, in streaming mode
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2665)
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2651)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1830)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:384)
	at com.intellij.util.io.HttpRequests$RequestImpl.readString(HttpRequests.java:438)
	at com.intellij.util.io.HttpRequests$Request.readString(HttpRequests.java:104)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:90)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator$doTranslate$2.process(AbstractTranslator.kt:21)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:516)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:498)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:56)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:349)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.doTranslate(AbstractTranslator.kt:88)
	at cn.yiiguxing.plugin.translate.trans.AbstractTranslator.translate(AbstractTranslator.kt:100)
	... 8 more
```

**Comment by masterhan1991** [comment]
之前一直用的好好的 突然今天不好用了 尝试将插件更新到最新版本 还是不好使 studio4.1的一直没动过

**Comment by masterhan1991** [comment]
在原作者那找到了答案 希望能帮到大家
https://github.com/YiiGuxing/TranslationPlugin/issues/821
